sudo: true

language: node_js

node_js:
  - 12

os:
  - window
  - osx

deploy:
  github_token: 0c6706a42ec103f61f537dd3273182fff481f73c # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

# Install scripts. (runs after repo cloning)
install:
  - npm install --build-from-source

# Post-install test scripts.
script:
  - npm run deploy
